site_name: EyeTrading
site_url: https://eyetrading.github.io/
# Repository
repo_name: EyeTrading/eyetrading.github.io
repo_url: https://github.com/eyetrading/eyetrading.github.io

nav:
  - Home: index.md
  - 使用說明:
    - 安裝與設定: guides/index.md
    - 軟體畫面: guides/screen_eyetrading.md
    - 下單畫面: guides/screen_flashbot.md
  - 免責聲明: disclaimer.md
  - About: about.md
  
theme:
  name: material
  language: zh-TW
  logo: assets/logo.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: amber
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      primary: amber
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

  icon:
    admonition:
      <type>: material/alert-circle

  # navigation
  features:
    - navigation.tabs
    #- navigation.tabs.sticky # show always
    #- navigation.sections
    #- navigation.indexes
    - toc.integrate

# footer
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://eyetrading.github.io
      name: EyeTrading on github

    - icon: fontawesome/solid/paper-plane
      link: mailto:<eyetrading77@gmail.com>
      name: squidfunk on Fosstodon

copyright: Copyright &copy; 2023 - 2024 EyeTrading
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
